version: '3'
services:
  bug-bounty:
    image: jakob/bug-bounty
    container_name: bug-bounty
    hostname: bug-bounty
    environment:
      - COLORTERM
      - TERM=xterm-256color
    build:
      context: .
